package words

var Words = map[string]string{
	// Ключевые слова
	"var":  "ёпта",
	"type": "чоткий",
	//"struct":      "",
	"case":  "чётут",
	"break": "впадлу",
	//"switch":      "",
	//"select":      "",
	"go": "погналинахуй",
	//"default":     "",
	"continue": "пиздуй",
	//"range":       "",
	"if":      "жизньворам",
	"else":    "хуймусорам",
	"package": "куку",
	"goto":    "шуруй",
	"func":    "нучё",
	"import":  "сюдапетуха",
	"defer":   "словоПацана",
	"chan":    "труба",
	//"fallthrough": "",
	"map": "поляна",
	//"interface":   "",
	//"for":         "",
	//"const":       "",
	"return": "безпизды",
	// Типы и алиасы
	"int":    "хуйня",
	"int8":   "хуйня8",
	"int16":  "хуйня16",
	"int32":  "хуйня32",
	"int64":  "хуйня64",
	"uint":   "безхуйни",
	"uint8":  "безхуйни8",
	"uint16": "безхуйни16",
	"uint32": "безхуйни32",
	"uint64": "безхуйни64",
	//"uintptr":    "",
	//"float32":    "",
	//"float64":    "",
	//"complex64":  "",
	//"complex128": "",
	//"string":     "",
	//"byte":       "",
	//"rune":       "",
	//"bool":       "",
	"nil":   "хуёво",
	"error": "егор",
	//"comparable": "",
	"true":  "внатуре",
	"false": "пиздишь",
	"any":   "всёхуйня",
	//"iota":       "",
	// built-in функции
	"print": "базарю",
	//"println": "",
	"len":  "скокатут",
	"make": "гони",
	//"copy":    "",
	//"new":     "",
	//"delete":  "",
	//"clear":   "",
	//"cap":     "",
	//"append":  "",
	//"close":   "",
	"panic":   "шухер",
	"recover": "отбой",
	//"min":     "",
	//"max":     "",
	//"complex": "",
	//"real":    "",
	//"imag":    "",
	// если перед этим словом стоит "нучё" или "куку", то заменяем на main
	"main": "пахан",
}
